import { addApiActionTypes } from '~/src/utils/api'

const actionTypes = {
  UPDATE_CAMPAIGN: `UPDATE_CAMPAIGN`,
  ADD_CAMPAIGN_CITY: `ADD_CAMPAIGN_CITY`,
  DELETE_CAMPAIGN_CITY: `DELETE_CAMPAIGN_CITY`,
  RESET_CAMPAIGN: `RESET_CAMPAIGN`,
  ADD_CAMPAIGN_CATEGORY: `ADD_CAMPAIGN_CATEGORY`,
  DELETE_CAMPAIGN_CATEGORY: `DELETE_CAMPAIGN_CATEGORY`,
  SUBMIT_CAMPAIGN: `SUBMIT_CAMPAIGN`,
  ADD_CAMPAIGN_POST: `ADD_CAMPAIGN_POST`,
  DELETE_CAMPAIGN_POST: `DELETE_CAMPAIGN_POST`,
  RESET_CAMPAIGN_FIELD: `RESET_CAMPAIGN_FIELD`,
}

addApiActionTypes(actionTypes, `API_GET_CAMPAIGN`)
addApiActionTypes(actionTypes, `API_GET_CAMPAIGNS`)
addApiActionTypes(actionTypes, `API_UPDATE_CAMPAIGN`)
addApiActionTypes(actionTypes, `API_ADD_POST`)
addApiActionTypes(actionTypes, `API_UPDATE_POST`)
addApiActionTypes(actionTypes, `API_DELETE_POST`)
addApiActionTypes(actionTypes, `API_ADD_SHARE`)

export default actionTypes