export const PLACE_AUTOCOMPLETE = `PLACE_AUTOCOMPLETE`
export const PLACE_AUTOCOMPLETE_FULFILLED = `PLACE_AUTOCOMPLETE_FULFILLED`
export const PLACE_AUTOCOMPLETE_FAILED = `PLACE_AUTOCOMPLETE_FAILED`
export const PLACE_AUTOCOMPLETE_PENDING = `PLACE_AUTOCOMPLETE_PENDING`
export const RESET_PLACE_AUTOCOMPLETE = `RESET_PLACE_AUTOCOMPLETE`