export const FB_LOGIN_FULFILLED = `FB_LOGIN_FULFILLED`
export const FB_LOGIN_FAILED = `FB_LOGIN_FAILED`
export const FB_LOGOUT_FULFILLED = `FB_LOGOUT_FULFILLED`
export const FB_LOGOUT_FAILED = `FB_LOGOUT_FAILED`